
from os import WTERMSIG


class Order():
    """
    This class is about the order generated by customers.
    """
    status = {
        1: 'ORDERED',
        2: 'DELIVERING',
        3: 'DELIVERED',
    }

    def __init__(self, index, t_in, customer, restaurant):
        self.index = index
        self.t = t_in # order in time
        self.cust = customer
        self.rest= restaurant
        self.rider = None
        self.status = 1
        self.t_delivered = -1
        self.wt = -1

    def getOrderStatus(self):
        return Order.status[self.status]

    def foundRider(self):
        self.status = 2
        # print("------ Order #" , self.index, "is assigned to Rider #", self.rider.index , "order is ", self.getOrderStatus() )
    
    def delivered(self, t_delivered):
        # order:
        self.status = 3
        self.t_delivered = t_delivered # update order delivered time
        self.wt = self.t_delivered - self.t
        # rider:
        self.rider.totalOrderDelivered += 1
        # customer
        self.cust.receivesOrder(self.t_delivered) # update user: received order
        # print("------ Order #" , self.index, "is", self.getOrderStatus(), "by Rider #", self.rider.index)
    
    def print(self):
        print("------ Order #" , self.index, "comes in at ", self.t, " and delivered at", self.t_delivered)
        # print("------ Order #" , self.index, "is ", self.getOrderStatus(), "\n Customer:", self.customer.loc, "Restaurant:", self.restaurant.loc)

    def __lt__(self, other):
        return self.t < other.t

    def reset(self):
        self.rider = None
        self.status = 1
        self.t_delivered = -1
        self.wt = -1


